### ISSUE TITLE
Shellout timeout при удалении tmp-dir

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#321]
```
it artifacts: latest patch ...                                                                [FAILED] 3659.66 sec
    signature: dimgstage-asdf-worker:d4a74fa6bb081ef6dfdcfd21343af9e4d0c2c68950c98d3f1f2a4d1ca32f3b07
Stacktrace dumped to /tmp/dapp-stacktrace-389259cc-6e3f-4d1d-a97e-d5037884aea6.out                  
/usr/local/rvm/gems/ruby-2.4.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout/unix.rb:124:in `run_command': Command timed out after 3600s: (Mixlib::ShellOut::CommandTimeout)
Command exceeded allowed execution time, process terminated                                         
---- Begin output of /usr/bin/docker run --rm --volume /tmp:/tmp alpine:3.6 rm -rf /tmp/dapp-20170713-22396-1orewpq ----
STDOUT:                                                                                             
STDERR:                                                                                             
---- End output of /usr/bin/docker run --rm --volume /tmp:/tmp alpine:3.6 rm -rf /tmp/dapp-20170713-22396-1orewpq ----
Ran /usr/bin/docker run --rm --volume /tmp:/tmp alpine:3.6 rm -rf /tmp/dapp-20170713-22396-1orewpq returned
    from /usr/local/rvm/gems/ruby-2.4.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:259:in `run_command'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/shellout/base.rb:22:in `block in shellout'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/shellout/base.rb:26:in `shellout'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/shellout/base.rb:64:in `_shellout_with_logging!'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/shellout/base.rb:36:in `shellout!'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/dimg.rb:177:in `cleanup_tmp' 
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/dimg.rb:41:in `ensure in build!'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/dimg.rb:41:in `build!'       
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/dapp/command/build.rb:11:in `block (2 levels) in build'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/logging/base.rb:50:in `block in log_step_with_indent'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/logging/base.rb:107:in `with_log_indent'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/logging/base.rb:49:in `log_step_with_indent'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dapp/logging/base.rb:44:in `log_dimg_name_with_indent'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/dapp/command/build.rb:10:in `block in build'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/dapp/command/build.rb:9:in `each'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/dapp/command/build.rb:9:in `build'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/cli/command/base.rb:6:in `public_send'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/dimg/cli/command/base.rb:6:in `run'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/helper/cli.rb:53:in `run_subcommand'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/cli.rb:49:in `run'                
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/helper/cli.rb:53:in `run_subcommand'
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/lib/dapp/cli.rb:49:in `run'                
    from /usr/local/rvm/gems/ruby-2.4.0/gems/dapp-0.13.4/bin/dapp:11:in `<top (required)>'          
    from /usr/local/rvm/gems/ruby-2.4.0/bin/dapp:22:in `load'                                       
    from /usr/local/rvm/gems/ruby-2.4.0/bin/dapp:22:in `<main>'                                     
    from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'                      
    from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'                    
ERROR: Job failed: execution took longer than 3600 seconds                                          
```

**Comment by distorhead** [comment]
Были проблемы с docker.
