### ISSUE TITLE
Игнорируется опция -r в  образе dappdeps/base при очистке перед монтированием

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#327]
```
$ dapp --version
dapp: 0.13.7
$ dapp dimg build --verbose
From ...   Launched command: `/.dapp/deps/base/0.1.15/bin/rm -rf /var/cache/apt && /.dapp/deps/base/0.1.15/bin/mkdir -p /var/cache/apt`
                                                                                                                                                                [FAILED] 0.42 sec
  signature: dimgstage-kobel169:cef9094fbb2fa8e8d4da6a2812808451498e6f19674999504436ccb5de8ce99a
Stacktrace dumped to /tmp/dapp-stacktrace-1cbef453-bb8a-4b33-9eb6-28da921191ab.out
>>> START STREAM
/.dapp/deps/base/0.1.15/bin/rm: cannot remove '/var/cache/apt': Directory not empty
>>> END STREAM

```

```
$ cat Dappfile
dimg do
  docker.from 'ruby:2.3-slim'
  mount '/var/cache/apt/' do
    from 'tmp_dir'
  end
end
```

```$ cat /tmp/dapp-stacktrace-1cbef453-bb8a-4b33-9eb6-28da921191ab.out
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/shellout/base.rb:66:in `rescue in _shellout_with_logging!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/shellout/base.rb:56:in `_shellout_with_logging!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/shellout/base.rb:36:in `shellout!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/image/stage.rb:73:in `run!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/image/stage.rb:25:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:221:in `block (2 levels) in image_build'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/logging/process.rb:83:in `block in log_process_default'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/logging/base.rb:99:in `with_log_indent'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/logging/process.rb:83:in `log_process_default'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/logging/process.rb:76:in `log_process_short'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/logging/process.rb:40:in `log_process'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:219:in `block in image_build'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/mod/logging.rb:12:in `log_image_build'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:218:in `image_build'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:52:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:51:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dimg.rb:33:in `block (3 levels) in build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:25:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:33:in `block (2 levels) in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/lock/base.rb:25:in `synchronize'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/lock.rb:18:in `lock'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:29:in `block in build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:45:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/build/stage/base.rb:43:in `build_lock!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dimg.rb:30:in `block (2 levels) in build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/lock/base.rb:25:in `synchronize'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/lock.rb:18:in `lock'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dimg.rb:29:in `block in build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dimg.rb:194:in `with_introspection'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dimg.rb:28:in `build!'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dapp/command/build.rb:11:in `block (2 levels) in build'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dapp/logging/base.rb:43:in `log_dimg_name_with_indent'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dapp/command/build.rb:10:in `block in build'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dapp/command/build.rb:9:in `each'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/dapp/command/build.rb:9:in `build'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/cli/command/base.rb:6:in `public_send'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/dimg/cli/command/base.rb:6:in `run'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/helper/cli.rb:53:in `run_subcommand'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/cli.rb:50:in `run'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/helper/cli.rb:53:in `run_subcommand'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/lib/dapp/cli.rb:50:in `run'
/usr/local/rvm/gems/ruby-2.3.0@dapp/gems/dapp-0.13.7/bin/dapp:11:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@dapp/bin/dapp:23:in `load'
/usr/local/rvm/gems/ruby-2.3.0@dapp/bin/dapp:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.0@dapp/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0@dapp/bin/ruby_executable_hooks:15:in `<main>'
```

```$ head -2  /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
```

**Comment by kobel169** [comment]
Не смог воспроизвести на хост-машине с ubuntu 16.04

**Comment by kobel169** [comment]
Проблема проявляется при использовании overlayfs 
Похожая проблема тут: https://github.com/moby/moby/issues/27358 

Не думаю что это проблема dapp.
